---
title: "Homework 9B"
author: "Shelbie Ishimaru"
date: "2024-10-27"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message= FALSE, #No messages as the default for all code chunks
                      warning= FALSE, #No warnings as the default for all code chunks
                      fig.path= "../Output/") #creates file path to save all plots 
```

#### Load Libraries
```{r}
library(tidyverse) #for data manipulation
library(here) #for unbreakable file paths
library(ggridges) #for creating ridge density plot
```

#### Read-in Data
```{r}
intertidal <- read_csv(here("Week_09","Data", "intertidaldata.csv")) #read in inter-tidal data
glimpse(intertidal) #look at data

intertidal_lat <- read_csv(here("Week_09","Data", "intertidaldata_latitude.csv")) #read in inter-tidal latitude data, so we can correctly factor the Site column 
glimpse(intertidal_lat) #look at data
```

#### Data Manipulation
```{r}
CA_tidal <- intertidal %>% #pull in inter-tidal data
  filter(Site== "Scripps" | #filter out to only 4 specific CA sites
           Site== "Dana Point" |
           Site== "Crystal Cove" |
           Site== "Little Corona") %>%
  mutate(Quadrat= recode(Quadrat, "Low  ."= "Low", #fix quadrat/tide values to be uniform
                         "Mid  1"= "Mid")) %>%
  mutate(Quadrat= factor(Quadrat, levels = c("High", #factor quadrat/tide column from high to low tide (for plotting legend)
                                             "Mid", 
                                             "Low"), ordered= T)) %>%
  mutate(Site= factor(Site, levels = c("Scripps", #factor the site column from lowest to highest latitude for plotting
                                       "Dana Point", 
                                       "Crystal Cove", 
                                       "Little Corona"), ordered= T))
```

#### Create Plot
```{r CA_intertidal}
cols <- c("dodgerblue4", "skyblue2", "lightsteelblue1") #color scheme for plot
#Plot 2: 
ggplot(CA_tidal, #use southern CA inter-tidal data
       aes(x= Algae, #x-axis is the percent cover of algae
           y= Site, #y-axis is the site
           fill= Quadrat)) + #fill by quadrat/tide level
  geom_density_ridges() + #make a density ridge plot
  theme_ridges() + #make a density ridge plot
  labs(x= "Percent Cover of Algae", #add x-axis label
       y= "Beach Sampling Location", #add y-axis label
       title= "Percent Algae Based on Ocean Tide in Southern California", #add title
       fill= "Ocean Tide") + #add legend title
  theme_bw() + #change theme so we have a white background with grey grid lines and black outline
  theme(axis.title= element_text(size= 11), #change axes text size
        plot.title= element_text(hjust= 0.5, #change title text size
                                 face= "bold")) + #make title bold
  geom_density_ridges(alpha = 0.5) + #make ridges transparent
  scale_fill_manual(values = cols) #use color scheme
    
```

